### PR TITLE
PeterPiper function

### PR DESCRIPTION
**Pull request by lidhigens**

### CODE REVIEW

**Comment by barberboy** [comment]
Hey, Kenneth! This implementation looks too similar to the one I wrote in class. Please rework it to use somewhat different logic.

For instance, try rewriting it to use only a single `if` statement by using the [Logical OR operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Logical_OR_%28%29) or [String#toLowerCase()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase)

**Comment by lidhigens** [comment]
I wrote this before you went over it in class. I had to wait until you went
over how to push it because I couldn't remember the code.

**Comment by barberboy** [comment]
Sorry, I still need you to change it.

**Comment by barberboy** [comment]
Yo, @lidhigens: I'm still waiting for you to update this with a different implementation.

**Comment by barberboy** [comment]
:+1:

**Pull request closed without merging**
